@include('student.includes.header')
@include('student.includes.top-navbar')
@include('student.includes.sidebar')
@yield('content')
@include('sweetalert::alert')
@include('student.includes.footer')
@include('student.includes.scripts')